name: EMCRecipies
version: ${project.version}
description: ${project.description}
author: creatorfromhell, KarlofDuty
website: https://earthmc.net
main: com.karlofduty.EMCRecipies.EMCRecipies
api-version: '1.16'
folia-supported: true
